### ISSUE TITLE
Installation with Makefile fails

### ISSUE THREAD

**Issue by florent-lamiraux** [agimus/agimus#3]
I am trying to write installation instruction for a demo using agimus. Following are the instructions that I try to run
```
cd $DEVEL_HPP_DIR/src
wget -O Makefile.agimus https://raw.githubusercontent.com/agimus/agimus/master/doc/Makefile
make -f Makefile.agimus bootstrap
make -f Makefile.agimus all
make -f Makefile.agimus agimus-demos.install
```
When running the third line, the makefile fails to set variable `AGIMUS_REPO` and therefore fails to checkout the first dependency `agimus_sot_msgs`:
    `git clone --quiet --recursive -b  /agimus_sot_msgs`
If I only try to checkout the same package
    `make -f Makefile.agimus agimus_sot_msgs.checkout`
it works, the Makefile thus correctly sets variable `AGIMUS_REPO`.

**Comment by jmirabel** [comment]
Which make target fails *bootstrap* or *all* ?

bootstrap just run `git clone --quiet --recursive https://github.com/agimus/agimus.git`. Did this work fine ?

**Comment by florent-lamiraux** [comment]
Target `all` fails.
I think I found the source of the problem. Variable `MAKE` used in some targets refers to `make` and not to `make -f Makefile.agimus`. Therefore, command `make` reads `Makefile` and not `Makefile.agimus`.

**Comment by florent-lamiraux** [comment]
And unfortunately, variable `MAKEFLAGS` does not keep option `-f`: let us consider a file named `Makefile.toto` containing the following lines:
```
all:
	@echo "MAKE=${MAKE}";
	@echo "MAKEFLAGS=${MAKEFLAGS}"
```
Command `make -f Makefile.toto` yields
```
MAKE=make
MAKEFLAGS=
```
I have to find another strategy.

**Comment by jmirabel** [comment]
Thanks. I think adding `-f $(firstword $(MAKEFILE_LIST))` should work.
